package com.steffenhebestreit.ai_research.Model;

import java.time.Instant;
import java.util.UUID;

/**
 * Represents an artifact produced by a task according to the A2A protocol.
 * 
 * An artifact is a unit of output from a task, such as a research report, summary,
 * data analysis, or other content generated by the agent. Each artifact has a type,
 * content type (MIME type), and the actual content.
 */
public class TaskArtifact {
    private String id;
    private String type;
    private String contentType;
    private String content;
    private Instant createdAt;

    /**
     * Default constructor.
     * 
     * Initializes an artifact with a randomly generated ID and the current timestamp.
     */
    public TaskArtifact() {
        this.id = UUID.randomUUID().toString();
        this.createdAt = Instant.now();
    }

    /**
     * Creates a new TaskArtifact with the specified type, content type, and content.
     * 
     * @param type The type of artifact (e.g., "literature-review", "data-analysis")
     * @param contentType The MIME type of the content (e.g., "text/plain", "text/html")
     * @param content The actual content of the artifact
     */
    public TaskArtifact(String type, String contentType, String content) {
        this.id = UUID.randomUUID().toString();
        this.type = type;
        this.contentType = contentType;
        this.content = content;
        this.createdAt = Instant.now();
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
